<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Player;

class 
PlayerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        Player::create([
            'first'=>'Kenan',
            'last'=>'Karaman',
            'role'=>'A',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Hakan',
            'last'=>'calhanoglu',
            'role'=>'C',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Cengiz',
            'last'=>'Under',
            'role'=>'C',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Orkun',
            'last'=>'Kokcu',
            'role'=>'C',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Halil',
            'last'=>'Dervisoglu',
            'role'=>'A',
            'team_id'=>'1']);
        Player::create([
            'first'=>'caglar',
            'last'=>'Soyuncu',
            'role'=>'D',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Kaan',
            'last'=>'Ayhan',
            'role'=>'D',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Mert',
            'last'=>'Muldur',
            'role'=>'D',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Mert',
            'last'=>'Gunok',
            'role'=>'P',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Mahmut',
            'last'=>'Tekdemir',
            'role'=>'C',
            'team_id'=>'1']);
        Player::create([
            'first'=>'İrfan Can',
            'last'=>'Kahveci',
            'role'=>'C',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Altay',
            'last'=>'Bayindir',
            'role'=>'P',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Gokhan',
            'last'=>'Akkan',
            'role'=>'P',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Dorukhan',
            'last'=>'Tokoz',
            'role'=>'D',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Zeki',
            'last'=>'celik',
            'role'=>'D',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Cengiz Umut',
            'last'=>'Meras',
            'role'=>'D',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Taylan',
            'last'=>'Antalyali',
            'role'=>'C',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Ugurcan',
            'last'=>'cakir',
            'role'=>'P',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Okay',
            'last'=>'Yokuslu',
            'role'=>'C',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Abdulkadir',
            'last'=>'omur',
            'role'=>'C',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Yusuf',
            'last'=>'Yazici',
            'role'=>'C',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Burak',
            'last'=>'Yilmaz',
            'role'=>'A',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Ozan',
            'last'=>'Tufan',
            'role'=>'D',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Halil',
            'last'=>'Akbunar',
            'role'=>'C',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Ozan',
            'last'=>'Kabak',
            'role'=>'D',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Efecan',
            'last'=>'Karaca',
            'role'=>'C',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Enes',
            'last'=>'Unal',
            'role'=>'A',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Merih',
            'last'=>'Demiral',
            'role'=>'D',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Ridvan',
            'last'=>'Yilmaz',
            'role'=>'D',
            'team_id'=>'1']);
        Player::create([
            'first'=>'Muhammed Kerem',
            'last'=>'Akturkoglu',
            'role'=>'C',
            'team_id'=>'1']);

        Player::create(['first'=>'Gianluigi','last'=>'Donnarumma','role'=>'P','team_id'=>'2']);Player::create(['first'=>'Leonardo','last'=>'Bonucci', 'role'=>'D','team_id'=>'2']);Player::create(['first'=>'Manuel','last'=>'Locatelli','role'=>'C','team_id'=>'2']);Player::create(['first'=>'Cristiano','last'=>'Biraghi', 'role'=>'D','team_id'=>'2']);Player::create(['first'=>'Federico','last'=>'Chiesa','role'=>'C','team_id'=>'2']);Player::create(['first'=>'Alessandro','last'=>'Florenzi','role'=>'C','team_id'=>'2']);Player::create(['first'=>'Lorenzo','last'=>'Pellegrini','role'=>'C','team_id'=>'2']);Player::create(['first'=>'Rafael','last'=>'Tolói', 'role'=>'D','team_id'=>'2']);Player::create(['first'=>'Alessandro','last'=>'Bastoni', 'role'=>'D','team_id'=>'2']);Player::create(['first'=>'Gianluca','last'=>'Mancini', 'role'=>'D','team_id'=>'2']);Player::create(['first'=>'Leonardo','last'=>'Spinazzola','role'=>'C','team_id'=>'2']);Player::create(['first'=>'Bryan','last'=>'Cristante','role'=>'C','team_id'=>'2']);Player::create(['first'=>'Alessio','last'=>'Cragno','role'=>'P','team_id'=>'2']);Player::create(['first'=>'Nicolò','last'=>'Barella','role'=>'C','team_id'=>'2']);Player::create(['first'=>'Giorgio','last'=>'Chiellini', 'role'=>'D','team_id'=>'2']);Player::create(['first'=>'Federico','last'=>'Bernardeschi','role'=>'C','team_id'=>'2']);Player::create(['first'=>'Ciro','last'=>'Immobile', 'role'=>'A','team_id'=>'2']);Player::create(['first'=>'Lorenzo','last'=>'Insigne','role'=>'C','team_id'=>'2']);Player::create(['first'=>'Moise','last'=>'Kean', 'role'=>'A','team_id'=>'2']);Player::create(['first'=>'Francesco','last'=>'Acerbi', 'role'=>'D','team_id'=>'2']);Player::create(['first'=>'Matteo','last'=>'Politano','role'=>'C','team_id'=>'2']);Player::create(['first'=>'Stefano','last'=>'Sensi','role'=>'C','team_id'=>'2']);Player::create(['first'=>'Domenico','last'=>'Berardi', 'role'=>'A','team_id'=>'2']);Player::create(['first'=>'Gian Marco','last'=>'Ferrari', 'role'=>'D','team_id'=>'2']);Player::create(['first'=>'Salvatore','last'=>'Sirigu','role'=>'P','team_id'=>'2']);Player::create(['first'=>'Andrea','last'=>'Belotti', 'role'=>'A','team_id'=>'2']);Player::create(['first'=>'Alex','last'=>'Meret','role'=>'P','team_id'=>'2']);Player::create(['first'=>'Manuel','last'=>'Lazzari','role'=>'C','team_id'=>'2']);Player::create(['first'=>'Giovanni','last'=>'Di Lorenzo', 'role'=>'D','team_id'=>'2']);Player::create(['first'=>'Gaetano','last'=>'Castrovilli','role'=>'C','team_id'=>'2']);Player::create(['first'=>'Matteo','last'=>'Pessina','role'=>'C','team_id'=>'2']);Player::create(['first'=>'Vincenzo','last'=>'Grifo','role'=>'C','team_id'=>'2']);Player::create(['first'=>'Marco','last'=>'Verratti','role'=>'C','team_id'=>'2']);Player::create(['first'=>'Roberto','last'=>'Mancini','role'=>'C','team_id'=>'2']);Player::create(['first'=>'Giacomo','last'=>'Raspadori', 'role'=>'A','team_id'=>'2']);

        Player::create(['first'=>'Gareth','last'=>'Bale','role'=>'C','team_id'=>'3']);Player::create(['first'=>'Tyler','last'=>'Roberts', 'role'=>'A','team_id'=>'3']);Player::create(['first'=>'Tom','last'=>'Lawrence','role'=>'C','team_id'=>'3']);Player::create(['first'=>'Chris','last'=>'Gunter', 'role'=>'D','team_id'=>'3']);Player::create(['first'=>'Rhys','last'=>'Norrington-Davies', 'role'=>'D','team_id'=>'3']);Player::create(['first'=>'David','last'=>'Brooks','role'=>'C','team_id'=>'3']);Player::create(['first'=>'Adam','last'=>'Davies','role'=>'P','team_id'=>'3']);Player::create(['first'=>'Kieffer','last'=>'Moore','role'=>'C','team_id'=>'3']);Player::create(['first'=>'Chris','last'=>'Mepham', 'role'=>'D','team_id'=>'3']);Player::create(['first'=>'Mark','last'=>'Harris','role'=>'C','team_id'=>'3']);Player::create(['first'=>'Tom','last'=>'Lockyer', 'role'=>'D','team_id'=>'3']);Player::create(['first'=>'Joe','last'=>'Rodon', 'role'=>'D','team_id'=>'3']);Player::create(['first'=>'Joe','last'=>'Morrell','role'=>'C','team_id'=>'3']);Player::create(['first'=>'Josh','last'=>'Sheehan','role'=>'C','team_id'=>'3']);Player::create(['first'=>'Thomas','last'=>'King','role'=>'P','team_id'=>'3']);Player::create(['first'=>'Aaron','last'=>'Ramsey','role'=>'C','team_id'=>'3']);Player::create(['first'=>'Ethan','last'=>'Ampadu','role'=>'C','team_id'=>'3']);Player::create(['first'=>'Danny','last'=>'Ward','role'=>'P','team_id'=>'3']);Player::create(['first'=>'Joe','last'=>'Allen','role'=>'C','team_id'=>'3']);Player::create(['first'=>'Daniel','last'=>'James','role'=>'C','team_id'=>'3']);Player::create(['first'=>'Connor','last'=>'Roberts','role'=>'C','team_id'=>'3']);Player::create(['first'=>'George','last'=>'Thomas','role'=>'C','team_id'=>'3']);Player::create(['first'=>'Wayne','last'=>'Hennessey','role'=>'P','team_id'=>'3']);Player::create(['first'=>'Harry','last'=>'Wilson','role'=>'C','team_id'=>'3']);Player::create(['first'=>'Benjamin','last'=>'Cabango', 'role'=>'D','team_id'=>'3']);Player::create(['first'=>'Jamie','last'=>'Lawrence', 'role'=>'D','team_id'=>'3']);Player::create(['first'=>'Matthew','last'=>'Smith','role'=>'C','team_id'=>'3']);Player::create(['first'=>'Rabbi','last'=>'Matondo', 'role'=>'A','team_id'=>'3']);Player::create(['first'=>'Neco','last'=>'Williams', 'role'=>'D','team_id'=>'3']);Player::create(['first'=>'Dylan','last'=>'Levitt','role'=>'C','team_id'=>'3']);

        Player::create(['first'=>'Fabian','last'=>'Schär', 'role'=>'D','team_id'=>'4']);Player::create(['first'=>'Manuel','last'=>'Akanji', 'role'=>'D','team_id'=>'4']);Player::create(['first'=>'Steven','last'=>'Zuber','role'=>'C','team_id'=>'4']);Player::create(['first'=>'Gregor','last'=>'Kobel','role'=>'P','team_id'=>'4']);Player::create(['first'=>'Ricardo','last'=>'Rodriguez', 'role'=>'D','team_id'=>'4']);Player::create(['first'=>'Remo','last'=>'Freuler','role'=>'C','team_id'=>'4']);Player::create(['first'=>'Silvan','last'=>'Widmer', 'role'=>'D','team_id'=>'4']);Player::create(['first'=>'Yann','last'=>'Sommer','role'=>'P','team_id'=>'4']);Player::create(['first'=>'Nico','last'=>'Elvedi', 'role'=>'D','team_id'=>'4']);Player::create(['first'=>'Granit','last'=>'Xhaka','role'=>'C','team_id'=>'4']);Player::create(['first'=>'Mario','last'=>'Gavranovic', 'role'=>'A','team_id'=>'4']);Player::create(['first'=>'Haris','last'=>'Seferovic', 'role'=>'A','team_id'=>'4']);Player::create(['first'=>'Breel','last'=>'Embolo', 'role'=>'A','team_id'=>'4']);Player::create(['first'=>'Denis','last'=>'Zakaria','role'=>'C','team_id'=>'4']);Player::create(['first'=>'Xherdan','last'=>'Shaqiri','role'=>'C','team_id'=>'4']);Player::create(['first'=>'Edimilson','last'=>'Fernandes','role'=>'C','team_id'=>'4']);Player::create(['first'=>'Admir','last'=>'Mehmedi', 'role'=>'A','team_id'=>'4']);Player::create(['first'=>'Yvon','last'=>'Mvogo','role'=>'P','team_id'=>'4']);Player::create(['first'=>'Loris','last'=>'Benito', 'role'=>'D','team_id'=>'4']);Player::create(['first'=>'Kevin','last'=>'Mbabu', 'role'=>'D','team_id'=>'4']);Player::create(['first'=>'Djibril','last'=>'Sow','role'=>'C','team_id'=>'4']);Player::create(['first'=>'Jordan','last'=>'Lotomba', 'role'=>'D','team_id'=>'4']);Player::create(['first'=>'Christian','last'=>'Fassnacht', 'role'=>'A','team_id'=>'4']);Player::create(['first'=>'Andi','last'=>'Zeqiri', 'role'=>'A','team_id'=>'4']);Player::create(['first'=>'Jonas','last'=>'Omlin','role'=>'P','team_id'=>'4']);Player::create(['first'=>'Eray','last'=>'Comert', 'role'=>'D','team_id'=>'4']);Player::create(['first'=>'Ruben','last'=>'Vargas', 'role'=>'A','team_id'=>'4']);Player::create(['first'=>'Dan','last'=>'Ndoye', 'role'=>'A','team_id'=>'4']);Player::create(['first'=>'Becir','last'=>'Omeragic', 'role'=>'D','team_id'=>'4']);

        Player::create(['first'=>'Simon','last'=>'Kjær', 'role'=>'D','team_id'=>'5']);Player::create(['first'=>'Andreas','last'=>'Cornelius', 'role'=>'A','team_id'=>'5']);Player::create(['first'=>'Jens Stryger','last'=>'Larsen','role'=>'C','team_id'=>'5']);Player::create(['first'=>'Joachim','last'=>'Andersen', 'role'=>'D','team_id'=>'5']);Player::create(['first'=>'Kasper','last'=>'Schmeichel','role'=>'P','team_id'=>'5']);Player::create(['first'=>'Jonas','last'=>'Lossl','role'=>'P','team_id'=>'5']);Player::create(['first'=>'Frederik','last'=>'Ronnow','role'=>'P','team_id'=>'5']);Player::create(['first'=>'Nicolai','last'=>'Boilesen', 'role'=>'D','team_id'=>'5']);Player::create(['first'=>'Mathias','last'=>'Jorgensen', 'role'=>'D','team_id'=>'5']);Player::create(['first'=>'Andreas','last'=>'Christensen', 'role'=>'D','team_id'=>'5']);Player::create(['first'=>'Christian','last'=>'Eriksen','role'=>'C','team_id'=>'5']);Player::create(['first'=>'Thomas','last'=>'Delaney','role'=>'C','team_id'=>'5']);Player::create(['first'=>'Yussuf','last'=>'Poulsen', 'role'=>'A','team_id'=>'5']);Player::create(['first'=>'Martin','last'=>'Braithwaite', 'role'=>'A','team_id'=>'5']);Player::create(['first'=>'Jannik','last'=>'Vestergaard', 'role'=>'D','team_id'=>'5']);Player::create(['first'=>'Kasper','last'=>'Dolberg', 'role'=>'A','team_id'=>'5']);Player::create(['first'=>'Pierre Emile','last'=>'Hojbjerg','role'=>'C','team_id'=>'5']);Player::create(['first'=>'Anders','last'=>'Christiansen','role'=>'C','team_id'=>'5']);Player::create(['first'=>'Joakim','last'=>'Mæhle', 'role'=>'D','team_id'=>'5']);Player::create(['first'=>'Daniel','last'=>'Wass','role'=>'C','team_id'=>'5']);Player::create(['first'=>'Mathias','last'=>'Jensen','role'=>'C','team_id'=>'5']);Player::create(['first'=>'Robert','last'=>'Skov','role'=>'C','team_id'=>'5']);Player::create(['first'=>'Jonas','last'=>'Wind', 'role'=>'A','team_id'=>'5']);Player::create(['first'=>'Christian','last'=>'Norgaard','role'=>'C','team_id'=>'5']);Player::create(['first'=>'Andreas Skov','last'=>'Olsen', 'role'=>'A','team_id'=>'5']);Player::create(['first'=>'Mikkel','last'=>'Damsgaard', 'role'=>'A','team_id'=>'5']);Player::create(['first'=>'Ebbe','last'=>'Sand', 'role'=>'A','team_id'=>'5']);

        Player::create(['first'=>'Sauli','last'=>'Väisänen', 'role'=>'D','team_id'=>'6']);Player::create(['first'=>'Niko','last'=>'Hämäläinen','role'=>'C','team_id'=>'6']);Player::create(['first'=>'Aapo','last'=>'Halme', 'role'=>'D','team_id'=>'6']);Player::create(['first'=>'Anssi','last'=>'Jaakkola','role'=>'P','team_id'=>'6']);Player::create(['first'=>'Joel','last'=>'Pohjanpalo', 'role'=>'A','team_id'=>'6']);Player::create(['first'=>'Lukás','last'=>'Hrádecký','role'=>'P','team_id'=>'6']);Player::create(['first'=>'Thomas','last'=>'Lam', 'role'=>'D','team_id'=>'6']);Player::create(['first'=>'Fredrik','last'=>'Jensen','role'=>'C','team_id'=>'6']);Player::create(['first'=>'Niki','last'=>'Mäenpää','role'=>'P','team_id'=>'6']);Player::create(['first'=>'Jere','last'=>'Uronen', 'role'=>'D','team_id'=>'6']);Player::create(['first'=>'Roope','last'=>'Riski', 'role'=>'A','team_id'=>'6']);Player::create(['first'=>'Albin','last'=>'Granlund', 'role'=>'D','team_id'=>'6']);Player::create(['first'=>'Jesse','last'=>'Joronen','role'=>'P','team_id'=>'6']);Player::create(['first'=>'Joni','last'=>'Kauko','role'=>'C','team_id'=>'6']);Player::create(['first'=>'Paulus','last'=>'Arajuuri', 'role'=>'D','team_id'=>'6']);Player::create(['first'=>'Teemu','last'=>'Pukki', 'role'=>'A','team_id'=>'6']);Player::create(['first'=>'Tim','last'=>'Sparv','role'=>'C','team_id'=>'6']);Player::create(['first'=>'Juhani','last'=>'Ojala', 'role'=>'D','team_id'=>'6']);Player::create(['first'=>'Carljohan','last'=>'Eriksson','role'=>'P','team_id'=>'6']);Player::create(['first'=>'Glen','last'=>'Kamara','role'=>'C','team_id'=>'6']);Player::create(['first'=>'Robert','last'=>'Taylor','role'=>'C','team_id'=>'6']);Player::create(['first'=>'Robin','last'=>'Lod','role'=>'C','team_id'=>'6']);Player::create(['first'=>'Onni','last'=>'Valakari','role'=>'C','team_id'=>'6']);Player::create(['first'=>'Robert','last'=>'Ivanov','role'=>'C','team_id'=>'6']);Player::create(['first'=>'Daniel','last'=>"O'Shaughnessy", 'role'=>'D','team_id'=>'6']);Player::create(['first'=>'Leo','last'=>'Väisänen', 'role'=>'D','team_id'=>'6']);Player::create(['first'=>'Lassi','last'=>'Lappalainen', 'role'=>'A','team_id'=>'6']);Player::create(['first'=>'Nikolai','last'=>'Alho', 'role'=>'A','team_id'=>'6']);Player::create(['first'=>'Jukka','last'=>'Raitala', 'role'=>'D','team_id'=>'6']);Player::create(['first'=>'Rasmus','last'=>'Schuller','role'=>'C','team_id'=>'6']);Player::create(['first'=>'Jasin','last'=>'Assehnoun','role'=>'C','team_id'=>'6']);Player::create(['first'=>'Pyry','last'=>'Soiri', 'role'=>'A','team_id'=>'6']);Player::create(['first'=>'Marcus','last'=>'Forss', 'role'=>'A','team_id'=>'6']);Player::create(['first'=>'Joona','last'=>'Toivio', 'role'=>'D','team_id'=>'6']);

        Player::create(['first'=>'Timothy','last'=>'Castagne', 'role'=>'D','team_id'=>'7']);Player::create(['first'=>'Dries','last'=>'Mertens', 'role'=>'A','team_id'=>'7']);Player::create(['first'=>'Dennis','last'=>'Praet','role'=>'C','team_id'=>'7']);Player::create(['first'=>'Simon','last'=>'Mignolet','role'=>'P','team_id'=>'7']);Player::create(['first'=>'Thibaut','last'=>'Courtois','role'=>'P','team_id'=>'7']);Player::create(['first'=>'Matz','last'=>'Sels','role'=>'P','team_id'=>'7']);Player::create(['first'=>'Thomas','last'=>'Vermaelen', 'role'=>'D','team_id'=>'7']);Player::create(['first'=>'Jan','last'=>'Vertonghen', 'role'=>'D','team_id'=>'7']);Player::create(['first'=>'Dedryck','last'=>'Boyata', 'role'=>'D','team_id'=>'7']);Player::create(['first'=>'Toby','last'=>'Alderweireld', 'role'=>'D','team_id'=>'7']);Player::create(['first'=>'Thomas','last'=>'Meunier', 'role'=>'D','team_id'=>'7']);Player::create(['first'=>'Eden','last'=>'Hazard','role'=>'C','team_id'=>'7']);Player::create(['first'=>'Kevin De','last'=>'Bruyne','role'=>'C','team_id'=>'7']);Player::create(['first'=>'Thorgan','last'=>'Hazard','role'=>'C','team_id'=>'7']);Player::create(['first'=>'Axel','last'=>'Witsel','role'=>'C','team_id'=>'7']);Player::create(['first'=>'Yannick','last'=>'Carrasco','role'=>'C','team_id'=>'7']);Player::create(['first'=>'Youri','last'=>'Tielemans','role'=>'C','team_id'=>'7']);Player::create(['first'=>'Leander','last'=>'Dendoncker','role'=>'C','team_id'=>'7']);Player::create(['first'=>'Romelu','last'=>'Lukaku', 'role'=>'A','team_id'=>'7']);Player::create(['first'=>'Michy','last'=>'Batshuayi', 'role'=>'A','team_id'=>'7']);Player::create(['first'=>'Nacer','last'=>'Chadli','role'=>'C','team_id'=>'7']);Player::create(['first'=>'Christian','last'=>'Benteke', 'role'=>'A','team_id'=>'7']);Player::create(['first'=>'Hans','last'=>'Vanaken','role'=>'C','team_id'=>'7']);Player::create(['first'=>'Leandro','last'=>'Trossard','role'=>'C','team_id'=>'7']);Player::create(['first'=>'Jason','last'=>'Denayer', 'role'=>'D','team_id'=>'7']);Player::create(['first'=>'Jeremy','last'=>'Doku', 'role'=>'A','team_id'=>'7']);

        Player::create(['first'=>'Andrei','last'=>'Semenov', 'role'=>'D','team_id'=>'8']);Player::create(['first'=>'Fedor','last'=>'Kudryashov', 'role'=>'D','team_id'=>'8']);Player::create(['first'=>'Yurii','last'=>'Zhirkov','role'=>'C','team_id'=>'8']);Player::create(['first'=>'Roman','last'=>'Zobnin','role'=>'C','team_id'=>'8']);Player::create(['first'=>'Aleksandr','last'=>'Golovin','role'=>'C','team_id'=>'8']);Player::create(['first'=>'Daler','last'=>'Kuzyaev','role'=>'C','team_id'=>'8']);Player::create(['first'=>'Denis','last'=>'Cheryshev', 'role'=>'A','team_id'=>'8']);Player::create(['first'=>'Anton','last'=>'Zabolotnyi', 'role'=>'A','team_id'=>'8']);Player::create(['first'=>'Vyacheslav','last'=>'Karavaev', 'role'=>'D','team_id'=>'8']);Player::create(['first'=>'Mário','last'=>'Fernandes', 'role'=>'D','team_id'=>'8']);Player::create(['first'=>'Artem','last'=>'Dzyuba', 'role'=>'A','team_id'=>'8']);Player::create(['first'=>'Georgii','last'=>'Dzhikiya', 'role'=>'D','team_id'=>'8']);Player::create(['first'=>'Andrei','last'=>'Mostovoi', 'role'=>'A','team_id'=>'8']);Player::create(['first'=>'Aleksandr','last'=>'Sobolev', 'role'=>'A','team_id'=>'8']);Player::create(['first'=>'Daniil','last'=>'Fomin','role'=>'C','team_id'=>'8']);Player::create(['first'=>'Stanislav','last'=>'Cherchesov','role'=>'C','team_id'=>'8']);Player::create(['first'=>'Anton','last'=>'Shunin','role'=>'P','team_id'=>'8']);Player::create(['first'=>'Matvei','last'=>'Safonov','role'=>'P','team_id'=>'8']);Player::create(['first'=>'Aleksei','last'=>'Ionov','role'=>'C','team_id'=>'8']);Player::create(['first'=>'Magomed','last'=>'Ozdoev','role'=>'C','team_id'=>'8']);Player::create(['first'=>'Rifat','last'=>'Zhemaletdinov', 'role'=>'A','team_id'=>'8']);Player::create(['first'=>'Ilya','last'=>'Samoshnikov','role'=>'C','team_id'=>'8']);Player::create(['first'=>'Igor','last'=>'Diveev', 'role'=>'D','team_id'=>'8']);Player::create(['first'=>'Denis','last'=>'Makarov','role'=>'C','team_id'=>'8']);Player::create(['first'=>'Roman','last'=>'Evgenjev', 'role'=>'D','team_id'=>'8']);Player::create(['first'=>'Maksim','last'=>'Mukhin','role'=>'C','team_id'=>'8']);

        Player::create(['first'=>'Rick','last'=>'Karsdorp','role'=>'C','team_id'=>'9']);Player::create(['first'=>'Hans','last'=>'Hateboer', 'role'=>'D','team_id'=>'9']);Player::create(['first'=>'Marten de','last'=>'Roon','role'=>'C','team_id'=>'9']);Player::create(['first'=>'Stefan de','last'=>'Vrij', 'role'=>'D','team_id'=>'9']);Player::create(['first'=>'Denzel','last'=>'Dumfries', 'role'=>'D','team_id'=>'9']);Player::create(['first'=>'Luuk de','last'=>'Jong', 'role'=>'A','team_id'=>'9']);Player::create(['first'=>'Steven','last'=>'Bergwijn', 'role'=>'A','team_id'=>'9']);Player::create(['first'=>'Donyell','last'=>'Malen', 'role'=>'A','team_id'=>'9']);Player::create(['first'=>'Jerry St.','last'=>'Juste', 'role'=>'D','team_id'=>'9']);Player::create(['first'=>'Tonny','last'=>'Vilhena','role'=>'C','team_id'=>'9']);Player::create(['first'=>'Steven','last'=>'Berghuis', 'role'=>'A','team_id'=>'9']);Player::create(['first'=>'Joel','last'=>'Veltman', 'role'=>'D','team_id'=>'9']);Player::create(['first'=>'Matthijs de','last'=>'Ligt', 'role'=>'D','team_id'=>'9']);Player::create(['first'=>'Donny van de','last'=>'Beek','role'=>'C','team_id'=>'9']);Player::create(['first'=>'Frenkie de','last'=>'Jong','role'=>'C','team_id'=>'9']);Player::create(['first'=>'Marco','last'=>'Bizot','role'=>'P','team_id'=>'9']);Player::create(['first'=>'Owen','last'=>'Wijndal', 'role'=>'D','team_id'=>'9']);Player::create(['first'=>'Teun','last'=>'Koopmeiners','role'=>'C','team_id'=>'9']);Player::create(['first'=>'Wout','last'=>'Weghorst', 'role'=>'A','team_id'=>'9']);Player::create(['first'=>'Maarten','last'=>'Stekelenburg','role'=>'P','team_id'=>'9']);Player::create(['first'=>'Davy','last'=>'Klaassen','role'=>'C','team_id'=>'9']);Player::create(['first'=>'Georginio','last'=>'Wijnaldum','role'=>'C','team_id'=>'9']);Player::create(['first'=>'Daley','last'=>'Blind', 'role'=>'D','team_id'=>'9']);Player::create(['first'=>'Patrick van','last'=>'Aanholt', 'role'=>'D','team_id'=>'9']);Player::create(['first'=>'Nathan','last'=>'Aké', 'role'=>'D','team_id'=>'9']);Player::create(['first'=>'Tim','last'=>'Krul','role'=>'P','team_id'=>'9']);Player::create(['first'=>'Anwar El','last'=>'Ghazi','role'=>'C','team_id'=>'9']);Player::create(['first'=>'Kenny','last'=>'Tete', 'role'=>'D','team_id'=>'9']);Player::create(['first'=>'Memphis','last'=>'Depay', 'role'=>'A','team_id'=>'9']);Player::create(['first'=>'Frank de','last'=>'Boer', 'role'=>'D','team_id'=>'9']);Player::create(['first'=>'Jasper','last'=>'Cillessen','role'=>'P','team_id'=>'9']);Player::create(['first'=>'Quincy','last'=>'Promes', 'role'=>'A','team_id'=>'9']);Player::create(['first'=>'Ryan','last'=>'Gravenberch','role'=>'C','team_id'=>'9']);Player::create(['first'=>'Jurrien','last'=>'Timber', 'role'=>'D','team_id'=>'9']);

        Player::create(['first'=>'Ádám','last'=>'Szalai', 'role'=>'A','team_id'=>'10']);Player::create(['first'=>'Ádám','last'=>'Lang', 'role'=>'D','team_id'=>'10']);Player::create(['first'=>'Ádam','last'=>'Nagy','role'=>'C','team_id'=>'10']);Player::create(['first'=>'Ádám','last'=>'Bogdán','role'=>'P','team_id'=>'10']);Player::create(['first'=>'Péter','last'=>'Gulácsi','role'=>'P','team_id'=>'10']);Player::create(['first'=>'Willi','last'=>'Orban', 'role'=>'D','team_id'=>'10']);Player::create(['first'=>'László','last'=>'Kleinheisler','role'=>'C','team_id'=>'10']);Player::create(['first'=>'Dániel','last'=>'Gazdag','role'=>'C','team_id'=>'10']);Player::create(['first'=>'Roland','last'=>'Sallai','role'=>'C','team_id'=>'10']);Player::create(['first'=>'Filip','last'=>'Holender', 'role'=>'A','team_id'=>'10']);Player::create(['first'=>'Dominik','last'=>'Szoboszlai','role'=>'C','team_id'=>'10']);Player::create(['first'=>'Akos','last'=>'Kecskés', 'role'=>'D','team_id'=>'10']);Player::create(['first'=>'Attila','last'=>'Fiola', 'role'=>'D','team_id'=>'10']);Player::create(['first'=>'Nemanja','last'=>'Nikolics', 'role'=>'A','team_id'=>'10']);Player::create(['first'=>'Gergo','last'=>'Lovrencsics', 'role'=>'A','team_id'=>'10']);Player::create(['first'=>'Dénes','last'=>'Dibusz','role'=>'P','team_id'=>'10']);Player::create(['first'=>'Tamás','last'=>'Cseri','role'=>'C','team_id'=>'10']);Player::create(['first'=>'János','last'=>'Hahn','role'=>'C','team_id'=>'10']);Player::create(['first'=>'Roland','last'=>'Varga', 'role'=>'A','team_id'=>'10']);Player::create(['first'=>'Endre','last'=>'Botka', 'role'=>'D','team_id'=>'10']);Player::create(['first'=>'Csaba','last'=>'Spandler', 'role'=>'D','team_id'=>'10']);Player::create(['first'=>'Loïc','last'=>'Nego', 'role'=>'D','team_id'=>'10']);Player::create(['first'=>'Dávid','last'=>'Sigér','role'=>'C','team_id'=>'10']);Player::create(['first'=>'Kevin','last'=>'Varga', 'role'=>'A','team_id'=>'10']);Player::create(['first'=>'Attila','last'=>'Szalai', 'role'=>'D','team_id'=>'10']);Player::create(['first'=>'Bendegúz','last'=>'Bolla','role'=>'C','team_id'=>'10']);Player::create(['first'=>'Balázs','last'=>'Tóth','role'=>'P','team_id'=>'10']);Player::create(['first'=>'András','last'=>'Schafer','role'=>'C','team_id'=>'10']);Player::create(['first'=>'Szabolcs','last'=>'Schon','role'=>'C','team_id'=>'10']);

        Player::create(['first'=>'Julian','last'=>'Baumgartlinger','role'=>'C','team_id'=>'11']);Player::create(['first'=>'David','last'=>'Alaba', 'role'=>'D','team_id'=>'11']);Player::create(['first'=>'Stefan','last'=>'Posch', 'role'=>'D','team_id'=>'11']);Player::create(['first'=>'Florian','last'=>'Grillitsch', 'role'=>'A','team_id'=>'11']);Player::create(['first'=>'Alessandro','last'=>'Schopf','role'=>'C','team_id'=>'11']);Player::create(['first'=>'Valentino','last'=>'Lazaro','role'=>'C','team_id'=>'11']);Player::create(['first'=>'Karim','last'=>'Onisiwo', 'role'=>'A','team_id'=>'11']);Player::create(['first'=>'Martin','last'=>'Hinteregger', 'role'=>'D','team_id'=>'11']);Player::create(['first'=>'Michael','last'=>'Gregoritsch', 'role'=>'A','team_id'=>'11']);Player::create(['first'=>'Christopher','last'=>'Trimmel','role'=>'C','team_id'=>'11']);Player::create(['first'=>'Aleksandar','last'=>'Dragovic', 'role'=>'D','team_id'=>'11']);Player::create(['first'=>'Daniel','last'=>'Bachmann','role'=>'P','team_id'=>'11']);Player::create(['first'=>'Marko','last'=>'Arnautovic', 'role'=>'A','team_id'=>'11']);Player::create(['first'=>'Marco','last'=>'Friedl', 'role'=>'D','team_id'=>'11']);Player::create(['first'=>'Philipp','last'=>'Lienhart', 'role'=>'D','team_id'=>'11']);Player::create(['first'=>'Stefan','last'=>'Ilsanker','role'=>'C','team_id'=>'11']);Player::create(['first'=>'Konrad','last'=>'Laimer','role'=>'C','team_id'=>'11']);Player::create(['first'=>'Marcel','last'=>'Sabitzer', 'role'=>'A','team_id'=>'11']);Player::create(['first'=>'Louis','last'=>'Schaub','role'=>'C','team_id'=>'11']);Player::create(['first'=>'Pavao','last'=>'Pervan','role'=>'P','team_id'=>'11']);Player::create(['first'=>'Alexander','last'=>'Schlager','role'=>'P','team_id'=>'11']);Player::create(['first'=>'Sasa','last'=>'Kalajdzic', 'role'=>'A','team_id'=>'11']);Player::create(['first'=>'Andreas','last'=>'Ulmer', 'role'=>'D','team_id'=>'11']);Player::create(['first'=>'Stefan','last'=>'Lainer', 'role'=>'D','team_id'=>'11']);Player::create(['first'=>'Xaver','last'=>'Schlager','role'=>'C','team_id'=>'11']);Player::create(['first'=>'Christoph','last'=>'Baumgartner','role'=>'C','team_id'=>'11']);

        Player::create(['first'=>'Goran','last'=>'Pandev', 'role'=>'A','team_id'=>'12']);Player::create(['first'=>'Aleksandar','last'=>'Trajkovski', 'role'=>'A','team_id'=>'12']);Player::create(['first'=>'Ezgjan','last'=>'Alioski', 'role'=>'D','team_id'=>'12']);Player::create(['first'=>'Gjoko','last'=>'Zajkov', 'role'=>'D','team_id'=>'12']);Player::create(['first'=>'Stefan','last'=>'Ristovski', 'role'=>'D','team_id'=>'12']);Player::create(['first'=>'Stefan','last'=>'Spirovski','role'=>'C','team_id'=>'12']);Player::create(['first'=>'Boban','last'=>'Nikolov', 'role'=>'A','team_id'=>'12']);Player::create(['first'=>'Visar','last'=>'Musliu', 'role'=>'D','team_id'=>'12']);Player::create(['first'=>'Milan','last'=>'Ristovski','role'=>'C','team_id'=>'12']);Player::create(['first'=>'Krste','last'=>'Velkoski', 'role'=>'A','team_id'=>'12']);Player::create(['first'=>'Arijan','last'=>'Ademi','role'=>'C','team_id'=>'12']);Player::create(['first'=>'Eljif','last'=>'Elmas','role'=>'C','team_id'=>'12']);Player::create(['first'=>'Enis','last'=>'Bardhi','role'=>'C','team_id'=>'12']);Player::create(['first'=>'Stole','last'=>'Dimitrievski','role'=>'P','team_id'=>'12']);Player::create(['first'=>'Darko','last'=>'Velkovski','role'=>'C','team_id'=>'12']);Player::create(['first'=>'Kire','last'=>'Ristevski', 'role'=>'D','team_id'=>'12']);Player::create(['first'=>'Egzon','last'=>'Bejtulai', 'role'=>'D','team_id'=>'12']);Player::create(['first'=>'Ferhan','last'=>'Hasani','role'=>'C','team_id'=>'12']);Player::create(['first'=>'Marjan','last'=>'Radeski', 'role'=>'A','team_id'=>'12']);Player::create(['first'=>'Daniel','last'=>'Avramovski','role'=>'C','team_id'=>'12']);Player::create(['first'=>'Risto','last'=>'Jankov','role'=>'P','team_id'=>'12']);Player::create(['first'=>'Darko','last'=>'Churlinov', 'role'=>'A','team_id'=>'12']);Player::create(['first'=>'Tihomir','last'=>'Kostadinov','role'=>'C','team_id'=>'12']);Player::create(['first'=>'Vlatko','last'=>'Stojanovski','role'=>'C','team_id'=>'12']);Player::create(['first'=>'Martin','last'=>'Bogatinov','role'=>'P','team_id'=>'12']);

        Player::create(['first'=>'Jadon','last'=>'Sancho','role'=>'C','team_id'=>'13']);Player::create(['first'=>'Jordan','last'=>'Pickford','role'=>'P','team_id'=>'13']);Player::create(['first'=>'Kyle','last'=>'Walker', 'role'=>'D','team_id'=>'13']);Player::create(['first'=>'Kieran','last'=>'Trippier', 'role'=>'D','team_id'=>'13']);Player::create(['first'=>'John','last'=>'Stones', 'role'=>'D','team_id'=>'13']);Player::create(['first'=>'Jordan','last'=>'Henderson','role'=>'C','team_id'=>'13']);Player::create(['first'=>'Jesse','last'=>'Lingard','role'=>'C','team_id'=>'13']);Player::create(['first'=>'Harry','last'=>'Maguire', 'role'=>'D','team_id'=>'13']);Player::create(['first'=>'Raheem','last'=>'Sterling', 'role'=>'A','team_id'=>'13']);Player::create(['first'=>'Marcus','last'=>'Rashford', 'role'=>'A','team_id'=>'13']);Player::create(['first'=>'Sam','last'=>'Johnstone','role'=>'P','team_id'=>'13']);Player::create(['first'=>'Jack','last'=>'Grealish','role'=>'C','team_id'=>'13']);Player::create(['first'=>'Conor','last'=>'Coady', 'role'=>'D','team_id'=>'13']);Player::create(['first'=>'Kalvin','last'=>'Phillips','role'=>'C','team_id'=>'13']);Player::create(['first'=>'Ollie','last'=>'Watkins', 'role'=>'A','team_id'=>'13']);Player::create(['first'=>'Dean','last'=>'Henderson','role'=>'P','team_id'=>'13']);Player::create(['first'=>'Ben','last'=>'Godfrey','role'=>'C','team_id'=>'13']);Player::create(['first'=>'Aaron','last'=>'Ramsdale','role'=>'P','team_id'=>'13']);Player::create(['first'=>'Ben','last'=>'White', 'role'=>'D','team_id'=>'13']);Player::create(['first'=>'Mason','last'=>'Mount','role'=>'C','team_id'=>'13']);Player::create(['first'=>'Dominic','last'=>'Calvert-Lewin', 'role'=>'A','team_id'=>'13']);Player::create(['first'=>'Trent','last'=>'Alexander-Arnold', 'role'=>'D','team_id'=>'13']);Player::create(['first'=>'Phil','last'=>'Foden','role'=>'C','team_id'=>'13']);Player::create(['first'=>'Luke','last'=>'Shaw', 'role'=>'D','team_id'=>'13']);Player::create(['first'=>'Harry','last'=>'Kane', 'role'=>'A','team_id'=>'13']);Player::create(['first'=>'Ben','last'=>'Chilwell', 'role'=>'D','team_id'=>'13']);Player::create(['first'=>'James','last'=>'Ward-Prowse','role'=>'C','team_id'=>'13']);Player::create(['first'=>'Declan','last'=>'Rice','role'=>'C','team_id'=>'13']);Player::create(['first'=>'Tyrone','last'=>'Mings', 'role'=>'D','team_id'=>'13']);Player::create(['first'=>'Gareth','last'=>'Southgate','role'=>'C','team_id'=>'13']);Player::create(['first'=>'Reece','last'=>'James', 'role'=>'D','team_id'=>'13']);Player::create(['first'=>'Bukayo','last'=>'Saka', 'role'=>'A','team_id'=>'13']);Player::create(['first'=>'Mason','last'=>'Greenwood', 'role'=>'A','team_id'=>'13']);Player::create(['first'=>'Jude','last'=>'Bellingham','role'=>'C','team_id'=>'13']);

        Player::create(['first'=>'Luka','last'=>'Modric','role'=>'C','team_id'=>'14']);Player::create(['first'=>'Mateo','last'=>'Kovacic','role'=>'C','team_id'=>'14']);Player::create(['first'=>'sime','last'=>'Vrsaljko', 'role'=>'D','team_id'=>'14']);Player::create(['first'=>'Andrej','last'=>'Kramaric', 'role'=>'A','team_id'=>'14']);Player::create(['first'=>'Milan','last'=>'Badelj','role'=>'C','team_id'=>'14']);Player::create(['first'=>'Marcelo','last'=>'Brozovic','role'=>'C','team_id'=>'14']);Player::create(['first'=>'Ivan','last'=>'Perisic','role'=>'C','team_id'=>'14']);Player::create(['first'=>'Bruno','last'=>'Petkovic', 'role'=>'A','team_id'=>'14']);Player::create(['first'=>'Ante','last'=>'Budimir', 'role'=>'A','team_id'=>'14']);Player::create(['first'=>'Lovre','last'=>'Kalinic','role'=>'P','team_id'=>'14']);Player::create(['first'=>'Dominik','last'=>'Livakovic','role'=>'P','team_id'=>'14']);Player::create(['first'=>'Domagoj','last'=>'Vida', 'role'=>'D','team_id'=>'14']);Player::create(['first'=>'Mario','last'=>'Pasalic','role'=>'C','team_id'=>'14']);Player::create(['first'=>'Ante','last'=>'Rebic', 'role'=>'A','team_id'=>'14']);Player::create(['first'=>'Nikola','last'=>'Vlasic','role'=>'C','team_id'=>'14']);Player::create(['first'=>'Dejan','last'=>'Lovren', 'role'=>'D','team_id'=>'14']);Player::create(['first'=>'Josip','last'=>'Brekalo', 'role'=>'A','team_id'=>'14']);Player::create(['first'=>'Duje','last'=>'caleta-Car', 'role'=>'D','team_id'=>'14']);Player::create(['first'=>'Borna','last'=>'Barisic', 'role'=>'D','team_id'=>'14']);Player::create(['first'=>'Simon','last'=>'Sluga','role'=>'P','team_id'=>'14']);Player::create(['first'=>'Josip','last'=>'Juranovic','role'=>'C','team_id'=>'14']);Player::create(['first'=>'Luka','last'=>'Ivanusec','role'=>'C','team_id'=>'14']);Player::create(['first'=>'Domagoj','last'=>'Bradaric', 'role'=>'D','team_id'=>'14']);Player::create(['first'=>'Mislav','last'=>'Orsic', 'role'=>'A','team_id'=>'14']);Player::create(['first'=>'Josko','last'=>'Gvardiol', 'role'=>'D','team_id'=>'14']);

        Player::create(['first'=>'Grant','last'=>'Hanley', 'role'=>'D','team_id'=>'15']);Player::create(['first'=>'Che','last'=>'Adams', 'role'=>'A','team_id'=>'15']);Player::create(['first'=>'Liam','last'=>'Cooper', 'role'=>'D','team_id'=>'15']);Player::create(['first'=>'John','last'=>'Fleck','role'=>'C','team_id'=>'15']);Player::create(['first'=>'Andrew','last'=>'Robertson', 'role'=>'D','team_id'=>'15']);Player::create(['first'=>'Scott','last'=>'McTominay','role'=>'C','team_id'=>'15']);Player::create(['first'=>'Ryan','last'=>'Fraser','role'=>'C','team_id'=>'15']);Player::create(['first'=>'David','last'=>'Marshall','role'=>'P','team_id'=>'15']);Player::create(['first'=>'Craig','last'=>'Gordon','role'=>'P','team_id'=>'15']);Player::create(['first'=>'James','last'=>'Forrest','role'=>'C','team_id'=>'15']);Player::create(['first'=>'Stuart','last'=>'Armstrong','role'=>'C','team_id'=>'15']);Player::create(['first'=>'Kieran','last'=>'Tierney', 'role'=>'D','team_id'=>'15']);Player::create(['first'=>'Callum','last'=>'McGregor','role'=>'C','team_id'=>'15']);Player::create(['first'=>'Jack','last'=>'Hendry', 'role'=>'D','team_id'=>'15']);Player::create(['first'=>'Scott','last'=>'McKenna', 'role'=>'D','team_id'=>'15']);Player::create(['first'=>'Ryan','last'=>'Christie','role'=>'C','team_id'=>'15']);Player::create(['first'=>'John','last'=>'McGinn','role'=>'C','team_id'=>'15']);Player::create(['first'=>'Jon','last'=>'McLaughlin','role'=>'P','team_id'=>'15']);Player::create(['first'=>'Kevin','last'=>'Nisbet', 'role'=>'A','team_id'=>'15']);Player::create(['first'=>'Greg','last'=>'Taylor','role'=>'C','team_id'=>'15']);Player::create(['first'=>'Stephen','last'=>"O'Donnell", 'role'=>'D','team_id'=>'15']);Player::create(['first'=>'David','last'=>'Turnbull','role'=>'C','team_id'=>'15']);Player::create(['first'=>'Lyndon','last'=>'Dykes', 'role'=>'A','team_id'=>'15']);Player::create(['first'=>'Declan','last'=>'Gallagher', 'role'=>'D','team_id'=>'15']);Player::create(['first'=>'Billy','last'=>'Gilmour','role'=>'C','team_id'=>'15']);Player::create(['first'=>'Nathan','last'=>'Patterson', 'role'=>'D','team_id'=>'15']);

        Player::create(['first'=>'Pavel','last'=>'Kaderábek','role'=>'C','team_id'=>'16']);Player::create(['first'=>'Patrik','last'=>'Schick', 'role'=>'A','team_id'=>'16']);Player::create(['first'=>'Jakub','last'=>'Jankto','role'=>'C','team_id'=>'16']);Player::create(['first'=>'Antonín','last'=>'Barák','role'=>'C','team_id'=>'16']);Player::create(['first'=>'Tomás','last'=>'Kalas', 'role'=>'D','team_id'=>'16']);Player::create(['first'=>'Matej','last'=>'Vydra', 'role'=>'A','team_id'=>'16']);Player::create(['first'=>'Vladimír','last'=>'Darida','role'=>'C','team_id'=>'16']);Player::create(['first'=>'Ales','last'=>'Mateju', 'role'=>'D','team_id'=>'16']);Player::create(['first'=>'Jakub','last'=>'Brabec', 'role'=>'D','team_id'=>'16']);Player::create(['first'=>'Jirí','last'=>'Pavlenka','role'=>'P','team_id'=>'16']);Player::create(['first'=>'Ales','last'=>'Mandous','role'=>'P','team_id'=>'16']);Player::create(['first'=>'Jan','last'=>'Boril', 'role'=>'D','team_id'=>'16']);Player::create(['first'=>'Tomás','last'=>'Soucek', 'role'=>'D','team_id'=>'16']);Player::create(['first'=>'Michal','last'=>'Krmencík', 'role'=>'A','team_id'=>'16']);Player::create(['first'=>'Tomás','last'=>'Vaclík','role'=>'P','team_id'=>'16']);Player::create(['first'=>'Tomás','last'=>'Pekhart', 'role'=>'A','team_id'=>'16']);Player::create(['first'=>'Ondrej','last'=>'celustka', 'role'=>'D','team_id'=>'16']);Player::create(['first'=>'Lukás','last'=>'Masopust','role'=>'C','team_id'=>'16']);Player::create(['first'=>'Alex','last'=>'Král','role'=>'C','team_id'=>'16']);Player::create(['first'=>'Vladimir','last'=>'Coufal', 'role'=>'D','team_id'=>'16']);Player::create(['first'=>'Petr','last'=>'sevcík','role'=>'C','team_id'=>'16']);Player::create(['first'=>'Tomás','last'=>'Holes', 'role'=>'D','team_id'=>'16']);Player::create(['first'=>'Jakub','last'=>'Pesek','role'=>'C','team_id'=>'16']);Player::create(['first'=>'Adam','last'=>'Hlozek', 'role'=>'A','team_id'=>'16']);Player::create(['first'=>'David','last'=>'Zima', 'role'=>'D','team_id'=>'16']);

        Player::create(['first'=>'Diego','last'=>'Llorente', 'role'=>'D','team_id'=>'17']);Player::create(['first'=>'Mikel','last'=>'Oiarzabal','role'=>'C','team_id'=>'17']);Player::create(['first'=>'Fabián','last'=>'Ruiz','role'=>'C','team_id'=>'17']);Player::create(['first'=>'Marcos','last'=>'Llorente','role'=>'C','team_id'=>'17']);Player::create(['first'=>'Pablo','last'=>'Sarabia','role'=>'C','team_id'=>'17']);Player::create(['first'=>'','last'=>'Koke','role'=>'C','team_id'=>'17']);Player::create(['first'=>'Thiago','last'=>'Alcântara','role'=>'C','team_id'=>'17']);Player::create(['first'=>'David De','last'=>'Gea','role'=>'P','team_id'=>'17']);Player::create(['first'=>'','last'=>'Azpilicueta', 'role'=>'D','team_id'=>'17']);Player::create(['first'=>'Jordi','last'=>'Alba', 'role'=>'D','team_id'=>'17']);Player::create(['first'=>'','last'=>'Rodri','role'=>'C','team_id'=>'17']);Player::create(['first'=>'Adama','last'=>'Traoré', 'role'=>'A','team_id'=>'17']);Player::create(['first'=>'Álvaro','last'=>'Morata', 'role'=>'A','team_id'=>'17']);Player::create(['first'=>'Aymeric','last'=>'Laporte', 'role'=>'D','team_id'=>'17']);Player::create(['first'=>'','last'=>'Busquets','role'=>'C','team_id'=>'17']);Player::create(['first'=>'Luis','last'=>'Enrique','role'=>'C','team_id'=>'17']);Player::create(['first'=>'Dani','last'=>'Olmo','role'=>'C','team_id'=>'17']);Player::create(['first'=>'Unai','last'=>'Simón','role'=>'P','team_id'=>'17']);Player::create(['first'=>'Gerard','last'=>'Moreno', 'role'=>'A','team_id'=>'17']);Player::create(['first'=>'Pau','last'=>'Torres', 'role'=>'D','team_id'=>'17']);Player::create(['first'=>'','last'=>'Gaya','role'=>'C','team_id'=>'17']);Player::create(['first'=>'Ferrán','last'=>'Torres', 'role'=>'A','team_id'=>'17']);Player::create(['first'=>'Eric','last'=>'García', 'role'=>'D','team_id'=>'17']);Player::create(['first'=>'','last'=>'Pedri', 'role'=>'A','team_id'=>'17']);Player::create(['first'=>'Robert','last'=>'Sánchez','role'=>'P','team_id'=>'17']);

        Player::create(['first'=>'Dejan','last'=>'Kulusevski', 'role'=>'A','team_id'=>'18']);Player::create(['first'=>'Emil','last'=>'Krafth', 'role'=>'D','team_id'=>'18']);Player::create(['first'=>'Filip','last'=>'Helander', 'role'=>'D','team_id'=>'18']);Player::create(['first'=>'Kristoffer','last'=>'Nordfeldt','role'=>'P','team_id'=>'18']);Player::create(['first'=>'Karl-Johan','last'=>'Johnsson','role'=>'P','team_id'=>'18']);Player::create(['first'=>'Martin','last'=>'Olsson', 'role'=>'D','team_id'=>'18']);Player::create(['first'=>'Andreas','last'=>'Granqvist', 'role'=>'D','team_id'=>'18']);Player::create(['first'=>'Mikael','last'=>'Lustig', 'role'=>'D','team_id'=>'18']);Player::create(['first'=>'Pontus','last'=>'Jansson', 'role'=>'D','team_id'=>'18']);Player::create(['first'=>'Victor','last'=>'Nilsson-Lindelöf', 'role'=>'D','team_id'=>'18']);Player::create(['first'=>'Sebastian','last'=>'Larsson','role'=>'C','team_id'=>'18']);Player::create(['first'=>'Emil','last'=>'Forsberg','role'=>'C','team_id'=>'18']);Player::create(['first'=>'Gustav','last'=>'Svensson','role'=>'C','team_id'=>'18']);Player::create(['first'=>'Viktor','last'=>'Claesson','role'=>'C','team_id'=>'18']);Player::create(['first'=>'Ken','last'=>'Sema','role'=>'C','team_id'=>'18']);Player::create(['first'=>'Markus','last'=>'Berg', 'role'=>'A','team_id'=>'18']);Player::create(['first'=>'Alexander','last'=>'Isak','role'=>'C','team_id'=>'18']);Player::create(['first'=>'Albin','last'=>'Ekdal','role'=>'C','team_id'=>'18']);Player::create(['first'=>'Robin','last'=>'Quaison','role'=>'C','team_id'=>'18']);Player::create(['first'=>'Ludwig','last'=>'Augustinsson', 'role'=>'D','team_id'=>'18']);Player::create(['first'=>'Mattias','last'=>'Svanberg','role'=>'C','team_id'=>'18']);Player::create(['first'=>'Robin','last'=>'Olsen','role'=>'P','team_id'=>'18']);Player::create(['first'=>'Marcus','last'=>'Danielson', 'role'=>'D','team_id'=>'18']);Player::create(['first'=>'Jordan','last'=>'Larsson', 'role'=>'A','team_id'=>'18']);Player::create(['first'=>'Kristoffer','last'=>'Olsson','role'=>'C','team_id'=>'18']);Player::create(['first'=>'Jens','last'=>'Cajuste','role'=>'C','team_id'=>'18']);

        Player::create(['first'=>'Robert','last'=>'Lewandowski', 'role'=>'A','team_id'=>'19']);Player::create(['first'=>'Wojciech','last'=>'Szczęsny','role'=>'P','team_id'=>'19']);Player::create(['first'=>'Piotr','last'=>'Zieliński','role'=>'C','team_id'=>'19']);Player::create(['first'=>'Arkadiusz','last'=>'Milik', 'role'=>'A','team_id'=>'19']);Player::create(['first'=>'Bartosz','last'=>'Bereszyński', 'role'=>'D','team_id'=>'19']);Player::create(['first'=>'Karol','last'=>'Linetty','role'=>'C','team_id'=>'19']);Player::create(['first'=>'Pawel','last'=>'Dawidowicz','role'=>'C','team_id'=>'19']);Player::create(['first'=>'Łukasz','last'=>'Fabiański','role'=>'P','team_id'=>'19']);Player::create(['first'=>'Kamil','last'=>'Glik', 'role'=>'D','team_id'=>'19']);Player::create(['first'=>'Grzegorz','last'=>'Krychowiak','role'=>'C','team_id'=>'19']);Player::create(['first'=>'Maciej','last'=>'Rybus','role'=>'C','team_id'=>'19']);Player::create(['first'=>'Mateusz','last'=>'Klich','role'=>'C','team_id'=>'19']);Player::create(['first'=>'Jan','last'=>'Bednarek', 'role'=>'D','team_id'=>'19']);Player::create(['first'=>'Przemysław','last'=>'Płacheta','role'=>'C','team_id'=>'19']);Player::create(['first'=>'Michał','last'=>'Helik', 'role'=>'D','team_id'=>'19']);Player::create(['first'=>'Kamil','last'=>'Jóźwiak','role'=>'C','team_id'=>'19']);Player::create(['first'=>'Karol','last'=>'Świderski', 'role'=>'A','team_id'=>'19']);Player::create(['first'=>'Jakub','last'=>'Moder','role'=>'C','team_id'=>'19']);

        Player::create(['first'=>'Milan','last'=>'Škriniar','role'=>'C','team_id'=>'20']);Player::create(['first'=>'Marek','last'=>'Hamšík','role'=>'C','team_id'=>'20']);Player::create(['first'=>'Marek','last'=>'Rodák','role'=>'P','team_id'=>'20']);Player::create(['first'=>'Peter','last'=>'Pekarík', 'role'=>'D','team_id'=>'20']);Player::create(['first'=>'Ondrej','last'=>'Duda','role'=>'C','team_id'=>'20']);Player::create(['first'=>'Martin','last'=>'Dúbravka','role'=>'P','team_id'=>'20']);Player::create(['first'=>'Denis','last'=>'Vavro', 'role'=>'D','team_id'=>'20']);Player::create(['first'=>'Jakub','last'=>'Holúbek','role'=>'C','team_id'=>'20']);Player::create(['first'=>'Patrik','last'=>'Hrošovský','role'=>'C','team_id'=>'20']);Player::create(['first'=>'Tomáš','last'=>'Hubočan', 'role'=>'D','team_id'=>'20']);Player::create(['first'=>'Matúš','last'=>'Bero','role'=>'C','team_id'=>'20']);Player::create(['first'=>'Juraj','last'=>'Kucka','role'=>'C','team_id'=>'20']);Player::create(['first'=>'Stanislav','last'=>'Lobotka','role'=>'C','team_id'=>'20']);Player::create(['first'=>'Róbert','last'=>'Mak','role'=>'C','team_id'=>'20']);Player::create(['first'=>'Vladimír','last'=>'Weiss','role'=>'C','team_id'=>'20']);Player::create(['first'=>'Michal','last'=>'Ďuriš', 'role'=>'A','team_id'=>'20']);Player::create(['first'=>'Dušan','last'=>'Kuciak','role'=>'P','team_id'=>'20']);Player::create(['first'=>'Erik','last'=>'Jirka','role'=>'C','team_id'=>'20']);Player::create(['first'=>'Ľubomír','last'=>'Šatka', 'role'=>'D','team_id'=>'20']);Player::create(['first'=>'Dávid','last'=>'Strelec','role'=>'C','team_id'=>'20']);Player::create(['first'=>'Lukáš','last'=>'Haraslín','role'=>'C','team_id'=>'20']);Player::create(['first'=>'Tomáš','last'=>'Suslov','role'=>'C','team_id'=>'20']);Player::create(['first'=>'Róbert','last'=>'Boženík', 'role'=>'A','team_id'=>'20']);

        Player::create(['first'=>'Ádám','last'=>'Szalai', 'role'=>'A','team_id'=>'21']);Player::create(['first'=>'Ádám','last'=>'Lang', 'role'=>'D','team_id'=>'21']);Player::create(['first'=>'Ádam','last'=>'Nagy','role'=>'C','team_id'=>'21']);Player::create(['first'=>'Ádám','last'=>'Bogdán','role'=>'P','team_id'=>'21']);Player::create(['first'=>'Péter','last'=>'Gulácsi','role'=>'P','team_id'=>'21']);Player::create(['first'=>'Willi','last'=>'Orban', 'role'=>'D','team_id'=>'21']);Player::create(['first'=>'László','last'=>'Kleinheisler','role'=>'C','team_id'=>'21']);Player::create(['first'=>'Dániel','last'=>'Gazdag','role'=>'C','team_id'=>'21']);Player::create(['first'=>'Roland','last'=>'Sallai','role'=>'C','team_id'=>'21']);Player::create(['first'=>'Filip','last'=>'Holender', 'role'=>'A','team_id'=>'21']);Player::create(['first'=>'Dominik','last'=>'Szoboszlai','role'=>'C','team_id'=>'21']);Player::create(['first'=>'Akos','last'=>'Kecskés', 'role'=>'D','team_id'=>'21']);Player::create(['first'=>'Attila','last'=>'Fiola', 'role'=>'D','team_id'=>'21']);Player::create(['first'=>'Nemanja','last'=>'Nikolics', 'role'=>'A','team_id'=>'21']);Player::create(['first'=>'Gergő','last'=>'Lovrencsics', 'role'=>'A','team_id'=>'21']);Player::create(['first'=>'Dénes','last'=>'Dibusz','role'=>'P','team_id'=>'21']);Player::create(['first'=>'Tamás','last'=>'Cseri','role'=>'C','team_id'=>'21']);Player::create(['first'=>'János','last'=>'Hahn','role'=>'C','team_id'=>'21']);Player::create(['first'=>'Roland','last'=>'Varga', 'role'=>'A','team_id'=>'21']);Player::create(['first'=>'Endre','last'=>'Botka', 'role'=>'D','team_id'=>'21']);Player::create(['first'=>'Csaba','last'=>'Spandler', 'role'=>'D','team_id'=>'21']);Player::create(['first'=>'Loïc','last'=>'Nego', 'role'=>'D','team_id'=>'21']);Player::create(['first'=>'Dávid','last'=>'Sigér','role'=>'C','team_id'=>'21']);Player::create(['first'=>'Kevin','last'=>'Varga', 'role'=>'A','team_id'=>'21']);Player::create(['first'=>'Attila','last'=>'Szalai', 'role'=>'D','team_id'=>'21']);Player::create(['first'=>'Bendegúz','last'=>'Bolla','role'=>'C','team_id'=>'21']);Player::create(['first'=>'Balázs','last'=>'Tóth','role'=>'P','team_id'=>'21']);Player::create(['first'=>'András','last'=>'Schafer','role'=>'C','team_id'=>'21']);Player::create(['first'=>'Szabolcs','last'=>'Schön','role'=>'C','team_id'=>'21']);

        Player::create(['first'=>'Cristiano','last'=>'Ronaldo', 'role'=>'A','team_id'=>'22']);Player::create(['first'=>'André','last'=>'Silva', 'role'=>'A','team_id'=>'22']);Player::create(['first'=>'João','last'=>'Cancelo', 'role'=>'D','team_id'=>'22']);Player::create(['first'=>'Rui','last'=>'Patrício','role'=>'P','team_id'=>'22']);Player::create(['first'=>'Anthony','last'=>'Lopes','role'=>'P','team_id'=>'22']);Player::create(['first'=>'José','last'=>'Fonte', 'role'=>'D','team_id'=>'22']);Player::create(['first'=>'Raphael','last'=>'Guerreiro', 'role'=>'D','team_id'=>'22']);Player::create(['first'=>'João','last'=>'Moutinho','role'=>'C','team_id'=>'22']);Player::create(['first'=>'William','last'=>'Carvalho','role'=>'C','team_id'=>'22']);Player::create(['first'=>'Bernardo','last'=>'Silva','role'=>'C','team_id'=>'22']);Player::create(['first'=>'Rúben','last'=>'Neves','role'=>'C','team_id'=>'22']);Player::create(['first'=>'Bruno','last'=>'Fernandes','role'=>'C','team_id'=>'22']);Player::create(['first'=>'Gonçalo','last'=>'Guedes', 'role'=>'A','team_id'=>'22']);Player::create(['first'=>'Diogo','last'=>'Jota', 'role'=>'A','team_id'=>'22']);Player::create(['first'=>'Renato','last'=>'Sanches', 'role'=>'A','team_id'=>'22']);Player::create(['first'=>'','last'=>'Pepe', 'role'=>'D','team_id'=>'22']);Player::create(['first'=>'Rúben','last'=>'Dias', 'role'=>'D','team_id'=>'22']);Player::create(['first'=>'Nélson','last'=>'Semedo', 'role'=>'D','team_id'=>'22']);Player::create(['first'=>'João','last'=>'Palhinha','role'=>'C','team_id'=>'22']);Player::create(['first'=>'Danilo','last'=>'Pereira','role'=>'C','team_id'=>'22']);Player::create(['first'=>'Sergio','last'=>'Oliveira','role'=>'C','team_id'=>'22']);Player::create(['first'=>'Rafa','last'=>'Silva','role'=>'C','team_id'=>'22']);Player::create(['first'=>'Rui','last'=>'Silva','role'=>'P','team_id'=>'22']);Player::create(['first'=>'João','last'=>'Félix', 'role'=>'A','team_id'=>'22']);Player::create(['first'=>'Pedro','last'=>'Gonçalves','role'=>'C','team_id'=>'22']);Player::create(['first'=>'Nuno','last'=>'Mendes', 'role'=>'D','team_id'=>'22']);

        Player::create(['first'=>'Karim','last'=>'Benzema', 'role'=>'A','team_id'=>'23']);Player::create(['first'=>'Clément','last'=>'Lenglet', 'role'=>'D','team_id'=>'23']);Player::create(['first'=>'Wissam Ben','last'=>'Yedder', 'role'=>'A','team_id'=>'23']);Player::create(['first'=>'Antoine','last'=>'Griezmann', 'role'=>'A','team_id'=>'23']);Player::create(['first'=>'Kingsley','last'=>'Coman','role'=>'C','team_id'=>'23']);Player::create(['first'=>'Corentin','last'=>'Tolisso','role'=>'C','team_id'=>'23']);Player::create(['first'=>'Hugo','last'=>'Lloris','role'=>'P','team_id'=>'23']);Player::create(['first'=>'Steve','last'=>'Mandanda','role'=>'P','team_id'=>'23']);Player::create(['first'=>'Lucas','last'=>'Digne', 'role'=>'D','team_id'=>'23']);Player::create(['first'=>'Raphael','last'=>'Varane', 'role'=>'D','team_id'=>'23']);Player::create(['first'=>'Presnel','last'=>'Kimpembe', 'role'=>'D','team_id'=>'23']);Player::create(['first'=>'Benjamin','last'=>'Pavard', 'role'=>'D','team_id'=>'23']);Player::create(['first'=>'Lucas','last'=>'Hernández', 'role'=>'D','team_id'=>'23']);Player::create(['first'=>'Paul','last'=>'Pogba','role'=>'C','team_id'=>'23']);Player::create(['first'=>"N'Golo",'last'=>'Kanté','role'=>'C','team_id'=>'23']);Player::create(['first'=>'Adrien','last'=>'Rabiot','role'=>'C','team_id'=>'23']);Player::create(['first'=>'Thomas','last'=>'Lemar', 'role'=>'A','team_id'=>'23']);Player::create(['first'=>'Olivier','last'=>'Giroud', 'role'=>'A','team_id'=>'23']);Player::create(['first'=>'Ousmane','last'=>'Dembélé', 'role'=>'A','team_id'=>'23']);Player::create(['first'=>'Kylian','last'=>'Mbappé', 'role'=>'A','team_id'=>'23']);Player::create(['first'=>'Kurt','last'=>'Zouma', 'role'=>'D','team_id'=>'23']);Player::create(['first'=>'Moussa','last'=>'Sissoko','role'=>'C','team_id'=>'23']);Player::create(['first'=>'Mike','last'=>'Maignan','role'=>'P','team_id'=>'23']);Player::create(['first'=>'Jules','last'=>'Koundé', 'role'=>'D','team_id'=>'23']);Player::create(['first'=>'Marcus','last'=>'Thuram-Ulien', 'role'=>'A','team_id'=>'23']);Player::create(['first'=>'Léo','last'=>'Dubois', 'role'=>'D','team_id'=>'23']);Player::create(['first'=>'Didier','last'=>'Deschamps','role'=>'C','team_id'=>'23']);

        Player::create(['first'=>'Toni','last'=>'Kroos','role'=>'C','team_id'=>'24']);Player::create(['first'=>'Kevin','last'=>'Volland', 'role'=>'A','team_id'=>'24']);Player::create(['first'=>'Kai','last'=>'Havertz','role'=>'C','team_id'=>'24']);Player::create(['first'=>'Serge','last'=>'Gnabry','role'=>'C','team_id'=>'24']);Player::create(['first'=>'Manuel','last'=>'Neuer','role'=>'P','team_id'=>'24']);Player::create(['first'=>'Mats','last'=>'Hummels', 'role'=>'D','team_id'=>'24']);Player::create(['first'=>'Niklas','last'=>'Sule', 'role'=>'D','team_id'=>'24']);Player::create(['first'=>'Joshua','last'=>'Kimmich','role'=>'C','team_id'=>'24']);Player::create(['first'=>'Thomas','last'=>'Muller', 'role'=>'A','team_id'=>'24']);Player::create(['first'=>'Robin','last'=>'Gosens','role'=>'C','team_id'=>'24']);Player::create(['first'=>'Bernd','last'=>'Leno','role'=>'P','team_id'=>'24']);Player::create(['first'=>'Kevin','last'=>'Trapp','role'=>'P','team_id'=>'24']);Player::create(['first'=>'Matthias','last'=>'Ginter', 'role'=>'D','team_id'=>'24']);Player::create(['first'=>'Antonio','last'=>'Rudiger', 'role'=>'D','team_id'=>'24']);Player::create(['first'=>'Leon','last'=>'Goretzka','role'=>'C','team_id'=>'24']);Player::create(['first'=>'Ilkay','last'=>'Gundogan','role'=>'C','team_id'=>'24']);Player::create(['first'=>'Emre','last'=>'Can','role'=>'C','team_id'=>'24']);Player::create(['first'=>'Leroy','last'=>'Sané', 'role'=>'A','team_id'=>'24']);Player::create(['first'=>'Timo','last'=>'Werner', 'role'=>'A','team_id'=>'24']);Player::create(['first'=>'Jonas','last'=>'Hofmann','role'=>'C','team_id'=>'24']);Player::create(['first'=>'Christian','last'=>'Gunter', 'role'=>'D','team_id'=>'24']);Player::create(['first'=>'Robin','last'=>'Koch', 'role'=>'D','team_id'=>'24']);Player::create(['first'=>'Florian','last'=>'Neuhaus','role'=>'C','team_id'=>'24']);Player::create(['first'=>'Lukas','last'=>'Klostermann', 'role'=>'D','team_id'=>'24']);Player::create(['first'=>'Marcel','last'=>'Halstenberg', 'role'=>'D','team_id'=>'24']);Player::create(['first'=>'Jamal','last'=>'Musiala','role'=>'C','team_id'=>'24']);
    }
}
